"""add pin to account

Revision ID: 4ae0528d9cec
Revises: 
Create Date: 2026-06-12 17:37:00.027642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae0528d9cec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('pin', sa.String(length=255), nullable=True))
    
    from app.security import get_password_hash
    default_pin = get_password_hash("0000")
    op.execute(f"UPDATE accounts SET pin = '{default_pin}'")

    op.drop_index(op.f('idx_accounts_user_id'), table_name='accounts')
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.drop_constraint(op.f('fk_accounts_user'), 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_id'), 'beneficiaries', ['id'], unique=False)
    op.drop_constraint(op.f('fk_beneficiary_user'), 'beneficiaries', type_='foreignkey')
    op.create_foreign_key(None, 'beneficiaries', 'users', ['user_id'], ['id'])
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_transactions_destination'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_source'), table_name='transactions')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_index(op.f('idx_transactions_source'), 'transactions', ['source_account_id'], unique=False)
    op.create_index(op.f('idx_transactions_reference'), 'transactions', ['reference_number'], unique=False)
    op.create_index(op.f('idx_transactions_destination'), 'transactions', ['destination_account_id'], unique=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'beneficiaries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_beneficiary_user'), 'beneficiaries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_beneficiaries_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_accounts_user'), 'accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.create_index(op.f('idx_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.drop_column('accounts', 'pin')
    # ### end Alembic commands ###
